### ISSUE TITLE
This package is not downloadable via the public url without login/password.

### ISSUE THREAD

**Issue by MaximilienNaveau** [laas/simple_humanoid_description#2]
I tried to clone this package with the public url, and it still asked my credentials. Is this normal?
Should this package be public so that no password is asked upon download with the public url (hhtps:// url?)

**Comment by mherrb** [comment]
It works for me.

Are you sure you don't have some github specific setup in your home
dir that lets git think you want to use your github account there ?

**Comment by MaximilienNaveau** [comment]
I tried with different computer and different account it works, this must be user specific then. Thanks @mherrb !
